from .CheXpert_Plus.CheXpert_Plus import CheXpert_Plus
from .CMB.CMB import CMB
from .CMExam.CMExam import CMExam
from .CMMLU.CMMLU import CMMLU
from .HealthBench.HealthBench import HealthBench
from .IU_XRAY.IU_XRAY import IU_XRAY
from .Medbullets_op4.Medbullets_op4 import Medbullets_op4
from .Medbullets_op5.Medbullets_op5 import Medbullets_op5
from .MedFrameQA.MedFrameQA import MedFrameQA
from .MedMCQA.MedMCQA import MedMCQA
from .MedQA_MCMLE.MedQA_MCMLE import MedQA_MCMLE
from .MedQA_USMLE.MedQA_USMLE import MedQA_USMLE
from .MedXpertQA.MedXpertQA import MedXpertQA
from .MIMIC_CXR.MIMIC_CXR import MIMIC_CXR
from .MMLU.MMLU import MMLU
from .MMMU.MMMU import MMMU
from .OmniMedVQA.OmniMedVQA import OmniMedVQA
from .PATH_VQA.PATH_VQA import PATH_VQA
from .PMC_VQA.PMC_VQA import PMC_VQA
from .PubMedQA.PubMedQA import PubMedQA
from .Radrestruct.Radrestruct import Radrestruct
from .SLAKE.SLAKE import SLAKE
from .SuperGPQA.SuperGPQA import SuperGPQA
from .VQA_RAD.VQA_RAD import VQA_RAD

from .CT_RATE.CT_RATE_LinearProbe import CT_RATE_LinearProbe
